"""empty message

Revision ID: 0380f303ed35
Revises: b13eec3dc2c0
Create Date: 2021-10-28 16:07:45.604641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0380f303ed35'
down_revision = 'b13eec3dc2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwor', sa.String(length=200), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user', 'passwor')
    # ### end Alembic commands ###
