"""empty message

Revision ID: ac46dda3acd9
Revises: 9b9860d42019
Create Date: 2021-11-02 10:27:48.343709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac46dda3acd9'
down_revision = '9b9860d42019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_name', sa.String(length=100), nullable=True),
    sa.Column('ability', sa.String(length=100), nullable=True),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.Column('base_hp', sa.Integer(), nullable=True),
    sa.Column('base_defense', sa.Integer(), nullable=True),
    sa.Column('base_attack', sa.Integer(), nullable=True),
    sa.Column('front_shiny', sa.String(length=600), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_pokemon_name'), 'pokemon', ['pokemon_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_pokemon_name'), table_name='pokemon')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
